### PR TITLE
add file ModTime() to real

### PR DESCRIPTION
**Pull request by terryh**
Hi, 
Thanks for this 'esc', I would like add the file ModTime() to work, 
which will serve the right Last-Modified header.

### CODE REVIEW

**Comment by mjibson** [comment]
I'd like to add this but want to be a bit cautious. Could you do an audit of the other go binary bundler packages and compare this solution to theirs?

**Comment by terryh** [comment]
OK, 
I took a look on 

https://github.com/rakyll/statik

this wrap text file into an zip archive.
type statikFS struct {
	files map[string]*zip.File
}
then every come back from the zip.File which hold the original modified time.

https://github.com/jteeuwen/go-bindata

this simple give each file the same modified time from the file parent folder via fix line like this
info := bindataFileInfo{name: "static/.DS_Store", size: 12292, mode: os.FileMode(420), modTime: time.Unix(1441176190, 0)}
and this their struct for FileInfo
type bindataFileInfo struct {
        name string
        size int64
        mode os.FileMode
        modTime time.Time
}

**Comment by terryh** [comment]
github.com/GeertJohan/go.rice

for this i saw they use zip to archive the real file, and add another layer
virtual file and virtual dir which all implement the os.FileInfo interface

but I never really use go.rice in my production, maybe someone else could give more information.

Thanks

**Comment by mjibson** [comment]
Please rebase master so you get the new travis build for this. After that passes I'll commit this.

**Comment by terryh** [comment]
Hi, 
I had rebased on your master branch, and add another commit to make gofmt happy, this up to you if you would like to merge.

Thanks

**Comment by mjibson** [comment]
Can you please rebase master onto this commit and do a force push with a single squished commit? If you aren't confident in your git skills to do that, then: make a new branch from my master, make a new commit with the changes to main.go, close this PR, make a new PR with that new commit.

**Comment by terryh** [comment]
No problem, just do a hard reset rebase on mater branch, squash to one commit.
and https://travis-ci.org/mjibson/esc/pull_requests passed

Thanks

**Pull request merged**
